#import "@/graphql/fragments/ContactFragment"
query ContactCategories($locale: String) {
  categories: ekfgroup_catalog_contacts_categories(
    where: { language: { code: { _eq: $locale } } }
    order_by: [{ sort_order: asc }, { id: asc }]
  ) {
    contacts(order_by: [{ sort_order: asc }, { id: asc }]) {
      ...ContactFragment

      settlement {
        fias_id
      }
    }

    name
  }
}
