#import "@/graphql/fragments/SearchProductFragment"
query SearchCatalog(
  $cartId: String
  $likeQuery: String!
  $limit: Int!
  $locale: String!
  $offset: Int!
  $page_url: String = ""
  $q: String!
  $sortBy: [ekfgroup_catalog_products_order_by!]
  $user_ip: inet = ""
  $where: ekfgroup_catalog_products_bool_exp!
) {
  products: ekfgroup_catalog_search_without_analog(
    args: { q: $q, page_url: $page_url, user_ip: $user_ip }
    where: {
      _or: [
        { _and: [$where, { price: { _gt: 0 } }] }
        { _and: [$where, { active: { _eq: false } }] }
      ]
    }
    limit: $limit
    offset: $offset
    order_by: $sortBy
  ) {
    ...SearchProductFragment

    stocks_aggregate {
      aggregate {
        sum {
          quantity
        }
      }
    }
  }

  totalRows: ekfgroup_catalog_search_without_analog_aggregate(
    args: { q: $q, page_url: $page_url, user_ip: $user_ip }
    where: $where
  ) {
    aggregate {
      count
      max {
        price
      }
      min {
        price
      }
    }
    nodes {
      categories {
        category {
          id
          name
        }
      }
    }
  }

  totalDocumentation: ekfgroup_catalog_products_aggregate(
    where: {
      language: { code: { _eq: $locale } }
      _or: [
        { name: { _ilike: $likeQuery } }
        { vendor_code: { _ilike: $likeQuery } }
      ]
      files: {
        file_type_id: {
          _in: [
            "373e91f9-64c9-11e8-a1fa-00155d00711b" # 3D Model
            "e4694427-f2ab-11ea-a219-00155dfa1116" # Application file
            "aaa3753c-688f-11e8-a1fa-00155d00711b" # Booklet
            "f79f43d4-5fd0-11e6-b98c-000c29c6d5f2" # Certificate
            "bfdce185-538f-11e7-80cc-0cc47a0cbffe" # Description
            "69ceaacc-73f7-11e6-971e-000c29c6d5f2" # Description and features
            "f79f43ce-5fd0-11e6-b98c-000c29c6d5f2" # Documentation
            "f79f43d5-5fd0-11e6-b98c-000c29c6d5f2" # Drawing
            "8585a500-704f-11e6-971e-000c29c6d5f2" # File for download
            "f79f43d1-5fd0-11e6-b98c-000c29c6d5f2" # Instruction
            "2cec8893-2a8f-11ec-a21d-00155d007700" # IES file
            "badfd70a-5784-11ee-a227-00155d29f504" # Manual
            "77527d49-735f-11e6-971e-000c29c6d5f2" # Master catalog
            "f79f43d3-5fd0-11e6-b98c-000c29c6d5f2" # Passport
            "a0ac8ef0-5784-11ee-a227-00155d29f504" # Patent
            "a0ac8eb9-5784-11ee-a227-00155d29f504" # Presentations
            "badfd7b5-5784-11ee-a227-00155d29f504" # Proof
            "31194e01-5785-11ee-a227-00155d29f504" # Questionnaire
            "b3fd1ce1-5784-11ee-a227-00155d29f504" # Rejection letter
            "aa11a788-73f7-11e6-971e-000c29c6d5f2" # Standard configuration
            "ad4c9135-704f-11e6-971e-000c29c6d5f2" # Table
            "993d6733-73f7-11e6-971e-000c29c6d5f2" # Технические характеристики
            "1c34d019-6893-11e8-a1fa-00155d00711b" # Референс
          ]
        }
      }
    }
  ) {
    aggregate {
      count
    }
  }

  totalNews: ekfgroup_catalog_articles_aggregate(
    where: {
      language: { code: { _eq: $locale } }
      _or: [
        { title: { _ilike: $likeQuery } }
        { short_text: { _ilike: $likeQuery } }
      ]
    }
  ) {
    aggregate {
      count
    }
  }
}
