#import "@/graphql/fragments/CompareProductFragment"
query CompareCategories($locale: String, $ids: [String!]) {
  categories: ekfgroup_catalog_categories(
    order_by: { name: asc }
    where: {
      language: { code: { _eq: $locale } }
      products: { product_id: { _in: $ids } }
      in_menu: { _eq: true }
    }
  ) {
    id
    name
    products_aggregate(where: { product_id: { _in: $ids } }) {
      aggregate {
        count
      }
    }
  }
}
