export const libraries = [
  {
    title: 'Revit',
    key: 'revit',
    image: '/images/libraries/revit-44.png',
    files: [
      {
        title:
          'Модульное оборудование (плагин TeslaBIM) v16.1, Revit 2019/2024',
        key: 'mo-tesla',
        type: 'zip',
        size: 198705152,
        href: 'https://api.ekfgroup.com/storage/revit/modular_equipment_(plugin Teslabim)_v_16.1_Revit_2017_2024.zip',
        external: false,
      },
      {
        title: 'Модульное оборудование (плагин Elprodject) v1.0',
        key: 'mo-el',
        type: 'zip',
        size: 225066921,
        href: 'https://api.ekfgroup.com/storage/revit/modular_equipment_(plugin elproject)_v_1.0_Revit_2017_2024.zip',
        external: false,
      },
      {
        title: 'Силовое оборудование (плагин TeslaBIM) v16.1, Revit 2019/2024',
        key: 'tesla-bim',
        type: 'zip',
        size: 198793225,
        href: 'https://api.ekfgroup.com/storage/revit/Power_equipment_(plugin Teslabim)_v_16.1_Revit_2017_2024.zip',
        external: false,
      },
      {
        title: 'Силовое оборудование (3D) v2.0',
        key: 'sil-3d',
        type: 'zip',
        size: 29909263,
        href: 'https://api.ekfgroup.com/storage/revit/Power_equipment_(3D)_v_2.0.zip',
        external: false,
      },
      {
        title: 'Системы прокладки кабеля (плагин EKF) v1.0',
        key: 'plugin-ekf',
        type: 'zip',
        size: 98269935,
        href: 'https://api.ekfgroup.com/storage/revit/Cable laying systems_(EKF_cable-tray-plugin)_v_1.0_Revit_2017-2024.zip',
        external: false,
      },
      {
        title: 'Системы прокладки кабеля v2.0',
        key: 'cabel-sys',
        type: 'zip',
        size: 281921419,
        href: 'https://api.ekfgroup.com/storage/revit/Cable laying systems_v_2.0.zip',
        external: false,
      },
      {
        title: 'Щиты корпуса и комплектующие v2.0',
        key: 'corpus',
        type: 'zip',
        size: 413536147,
        href: 'https://api.ekfgroup.com/storage/revit/Body_shields_and_accessories_v_2.0.zip',
        external: false,
      },
      {
        title:
          'Щиты корпуса и комплектующие (плагин TeslaBIM) v16.1, Revit 2019/2024',
        key: 'corpus-tesla-bim',
        type: 'zip',
        size: 198793225,
        href: 'https://api.ekfgroup.com/storage/revit/Shields_enclosures_and_accessories_v_2.0_(plugin Teslabim)_v_16.1_Revit_2017_2024.zip',
        external: false,
      },
      {
        title: 'Электроустановочные изделия v2.0',
        key: 'eui',
        type: 'zip',
        size: 416808960,
        href: 'https://api.ekfgroup.com/storage/revit/elektroustanovka_v_2.0.zip',
        external: false,
      },
      {
        title: 'Светотехника v2.0',
        key: 'light',
        type: 'zip',
        size: 4400994,
        href: 'https://api.ekfgroup.com/storage/revit/lighting engineering_v_2.0.zip',
        external: false,
      },
      {
        title: 'Измерительная аппаратура v2.0',
        key: 'count',
        type: 'zip',
        size: 5423059,
        href: 'https://api.ekfgroup.com/storage/revit/Measuring_equipment_v_2.0.zip',
        external: false,
      },
      {
        title: 'Молниезащита (плагин EKF) v1.0',
        key: 'molni',
        type: 'zip',
        size: 566820,
        href: 'https://api.ekfgroup.com/storage/revit/lightning_protection_(EKF-plugin)_v_1.0_Revit_2017-2024.zip',
        external: false,
      },
    ],
    fileAll: {
      title: 'Скачать всё',
      type: 'zip',
      size: 1674736285,
      href: 'https://api.ekfgroup.com/storage/revit/Revit_Archive.zip',
      external: false,
    },
  },
  {
    title: 'Autocad',
    key: 'autocad',
    image: '/images/libraries/autocad-44.png',
    files: [
      {
        title: 'Инструкция по установке EKF для AutoCAD Electrical',
        key: 'installation',
        type: 'pdf',
        size: 1876951,
        href: 'https://cloud.ekf.su/s/gZ5PDC3kqnYStbe',
        external: true,
      },
      {
        title: 'Элементная база для создания планов',
        key: 'planBase',
        type: 'dwg',
        size: 10905190,
        href: 'https://cloud.ekf.su/s/YHLAAQHPzw3wJEY',
        external: true,
      },
      {
        title: 'Элементная база для создания схем',
        key: 'schemeBase',
        type: 'dwg',
        size: 82103501,
        href: 'https://cloud.ekf.su/s/T8Z8bJsw9i6mcmJ',
        external: true,
      },
      {
        title: 'База EKF для AutoCAD Electrical',
        key: 'electricalBase',
        type: 'rar',
        size: 74553754,
        href: 'https://cloud.ekf.su/s/NgMpqjWkBc2BbRJ',
        external: true,
      },
      {
        title: 'Динамические блоки лотков',
        key: 'dynamicTrayBlocks',
        type: 'dwg',
        size: 16043213,
        href: 'https://cloud.ekf.su/s/PEt3ZRzifZYCQZi',
        external: true,
      },
      {
        title: 'База для планов МЗ 3D молниезащита',
        key: 'lightningProtectionBase3d',
        type: 'dwg',
        size: 608174,
        href: 'https://cloud.ekf.su/s/8swxkQcC4iNiE7L',
        external: true,
      },
      {
        title: 'Молниеприемники',
        key: 'lightningRods',
        type: 'xlsm',
        size: 31792,
        href: 'https://cloud.ekf.su/s/PzA7ptPTtNdDqSD',
        external: true,
      },
      {
        title: 'База для планов EKF МЗ Купол',
        key: 'lightningProtectionBaseKupol',
        type: 'dwg',
        size: 6501171,
        href: 'https://cloud.ekf.su/s/GNLzfxFf3f2Y7R8',
        external: true,
      },
      {
        title: 'Элементная база светильников',
        key: 'lightBase',
        type: 'dwg',
        size: 3145728,
        href: 'https://cloud.ekf.su/s/btTg86bZnCYeetz',
        external: true,
      },
      {
        title:
          'Автоматическое создание спецификации с компоновкой по комплектам',
        key: 'autoSpecKits',
        type: 'lsp',
        size: 7600,
        href: 'https://cloud.ekf.su/s/zSWw8tFia3LHBLE',
        external: true,
      },
      {
        title:
          'Автоматическое создание спецификации без компоновки по комплектам',
        key: 'autoSpec',
        type: 'lsp',
        size: 6941,
        href: 'https://cloud.ekf.su/s/KxbfeMiayXPeRmw',
        external: true,
      },
      {
        title: 'Инструкция по автоматическому созданию спецификации',
        key: 'autoSpecManual',
        type: 'docx',
        size: 433071,
        href: 'https://cloud.ekf.su/s/koT9s9FyRkbxyJW',
        external: true,
      },
      {
        title: 'Типовые схемы',
        key: 'typicalSchemes',
        type: '7z',
        size: 4204736,
        href: 'https://cloud.ekf.su/s/gcHzr2EwGgstoHX',
        external: true,
      },
    ],
  },
  {
    title: 'nanoCAD',
    key: 'nanocad',
    image: '/images/libraries/nanocad-44.png',
    files: [
      {
        title: 'Модульное оборудование v2.0',
        key: 'mo-2',
        type: 'zip',
        size: 160131034,
        href: 'https://api.ekfgroup.com/storage/nanocad/modular_equipmen_v_2.0.zip',
        external: false,
      },
      {
        title: 'Силовое оборудование v2.0',
        key: 'so-2',
        type: 'zip',
        size: 200818858,
        href: 'https://api.ekfgroup.com/storage/nanocad/Power_equipment_v_2.0.zip',
        external: false,
      },
      {
        title: 'Автоматиация и КИП v2.0',
        key: 'kip-2',
        type: 'zip',
        size: 147817345,
        href: 'https://api.ekfgroup.com/storage/nanocad/Automation_and_instrumentation_v_2.0.zip',
        external: false,
      },
      {
        title: 'Системы прокладки кабеля v2.0',
        key: 'spk-2',
        type: 'zip',
        size: 20992944,
        href: 'https://api.ekfgroup.com/storage/nanocad/Cable_laying_systems_v_2.0.zip',
        external: false,
      },
      {
        title: 'Щиты корпуса и комплектующие v2.0',
        key: 'corpusa-2',
        type: 'zip',
        size: 85460410,
        href: 'https://api.ekfgroup.com/storage/nanocad/Shields_enclosures_and_accessories_v_2.0.zip',
        external: false,
      },
      {
        title: 'Электроустановочные изделия v2.0',
        key: 'eui-2',
        type: 'zip',
        size: 81485539,
        href: 'https://api.ekfgroup.com/storage/nanocad/elektroustanovka_v_2.0.zip',
        external: false,
      },
      {
        title: 'Светотехника v2.0',
        key: 'sveto-2',
        type: 'zip',
        size: 9494715,
        href: 'https://api.ekfgroup.com/storage/nanocad/lighting_engineering_v_2.0.zip',
        external: false,
      },
      {
        title: 'Измерительная аппаратура v2.0',
        key: 'ia-2',
        type: 'zip',
        size: 22395072,
        href: 'https://api.ekfgroup.com/storage/nanocad/Measuring_equipment_v_2.0.zip',
        external: false,
      },
      {
        title: 'Молниезащита v2.0',
        key: 'molni-2',
        type: 'zip',
        size: 9011516,
        href: 'https://api.ekfgroup.com/storage/nanocad/lightning_protection_v_2.0.zip',
        external: false,
      },
      {
        title: 'Оборудование среднего напряжения v2.0',
        key: 'osn-2',
        type: 'zip',
        size: 3780377,
        href: 'https://api.ekfgroup.com/storage/nanocad/Medium_voltage_equipment_v_2.0.zip',
        external: false,
      },
      {
        title: 'Телекоммуникационное оборудование v2.0',
        key: 'to-2',
        type: 'zip',
        size: 4023471,
        href: 'https://api.ekfgroup.com/storage/nanocad/Telecommunication_equipment_TERACOM_v_2.0.zip',
        external: false,
      },
      {
        title: 'Бытовые звонки и домофоны 2.0',
        key: 'bzd-2',
        type: 'zip',
        size: 1596422,
        href: 'https://api.ekfgroup.com/storage/nanocad/Household_calls_and_intercoms__v_2.0.zip',
        external: false,
      },
      {
        title: 'Программы и дополнительное оборудование',
        key: 'pido',
        type: 'zip',
        size: 265650450,
        href: 'https://api.ekfgroup.com/storage/nanocad/programmy-i-dopolnitelnoe-oborudovanie.zip',
        external: false,
      },
    ],
    fileAll: {
      title: 'Скачать всё',
      type: 'zip',
      size: 1012655308,
      href: 'https://api.ekfgroup.com/storage/nanocad/nanoCAD_Archive.zip',
      external: false,
    },
  },
  {
    title: 'EPLAN',
    key: 'eplan',
    image: '/images/libraries/eplan-44.png',
    href: 'https://cloud.ekf.su/s/qwqiL2wPt6d8xkw',
    external: true,
    linkText: 'Скачать архив (ZIP, 255)',
    type: 'zip',
    size: 267386880,
  },
  {
    title: '3D модели',
    key: 'models',
    image: '/images/libraries/3dmodels-44.png',
    to: '/support/documentation',
    linkText: 'Перейти к 3D моделям',
  },
]

export default {}
