export const warrantyCategories = [
  {
    name: '01 Автоматические выключатели модульные и доп. устройства',
    children: [
      {
        name: '01.01 Выключатели автоматические AV-6 до 63А EKF AVERES',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '01.02 Выключатели автоматические AV-10 до 63А EKF AVERES',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '01.03 Выключатели автоматические AV-6 DC до 63А EKF AVERES',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '01.05 Выключатели автоматические ВА 47-63 4.5кА до 63А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '01.06 Выключатели автоматические ВА 47-63 6кА до 63А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '01.07 Выключатели автоматические ВА 47-100 (10кА) до 125А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '01.08 Выключатели автоматические ВА 47-125 (15кА) до 125А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '01.09 Выключатели автоматические ВА 47-29 (4.5кА) до 63А EKF Basic',
        servicePeriod: '3',
        storagePeriod: '3',
        lifeTime: '8',
      },
      {
        name: '01.10 Дополнительные устройства на DIN-рейку EKF AVERES',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '01.11 Дополнительные устройства на DIN-рейку EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '02 Автоматические выключатели дифференциального тока и УЗО',
    children: [
      {
        name: '02.03.01.01 DV EKF AVERES 30 мА',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '02.03.01.01 Дифференциальные автоматы серии АД-2, АД-4 4,5кА с отключающим диф. током 10мА, 30мА EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '02.03.01.02 DV EKF AVERES 100 мА',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '02.03.01.02 Дифференциальные автоматы серии АД-2, АД-4 4,5кА с отключающим диф. током 100мА EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '02.03.01.03 DV EKF AVERES 300 мА',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '02.03.01.03 Дифференциальные автоматы серии АД-2S, АД-4S 4,5кА селективные с отключающим диф. током 100мА, 300мА EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '02.03.01.04 Дифференциальные автоматы серии АД-2, АД-4 4,5кА с отключающим диф. током 300мА EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '02.03.02.01 DV EKF AVERES 30 мА',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '02.03.02.02 DV EKF AVERES 100 мА',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '02.03.02.03 DV EKF AVERES 300 мА',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '02.03.02.05 DV EKF AVERES 10 мА',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '02.03.04.02 DV EKF AVERES 300 мА',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '02.04 Дифференциальные автоматы АВДТ до 63А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '02.06 Дифференциальные автоматы АД-12 до 63А EKF Basic',
        servicePeriod: '3',
        storagePeriod: '3',
        lifeTime: '8',
      },
      {
        name: '02.08 Устройства защитного отключения (УЗО) ВДТ-40 до 63А EKF Basic',
        servicePeriod: '3',
        storagePeriod: '3',
        lifeTime: '8',
      },
    ],
  },
  {
    name: '03 Устройства защиты от импульсных перенапряжений',
    children: [
      {
        name: '03.01 Устр-во защиты от импульсных перенапряжений (УЗИП) ОПВ EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '03.02 Устро-во защиты от импульсных перенапряжений (УЗИП) Тип 1 EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '04 Автоматические выключатели в литом корпусе до 1600А',
    children: [
      {
        name: '04.01 Выключатели силовые до 1600А AV Power EKF AVERES',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '04.02 Аксессуары для выключателей силовых AV Power EKF AVERES',
        servicePeriod: '5',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '04.03 Выключатели автоматические ВА-99 до 1600А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '04.04 Аксессуары для выключателей автоматических ВА-99 EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '04.05 Выключатели автоматические ВА-99С (Compact NS) до 1600А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '04.06 Аксессуары для выключателей автоматических ВА-99С (Compact NS)',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '04.07 Аксессуары для выключателей автоматических ВА-99М EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '04.08 Выключатели автоматические ВА-99МL до 250А 15-20кА EKF Basic',
        servicePeriod: '3',
        storagePeriod: '5',
        lifeTime: '10',
      },
      {
        name: '04.09 Выключатели автоматические ВА-99М до 1600А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '05 Автоматические выключатели воздушные до 6300А',
    children: [
      {
        name: '05.01 Выключатели автоматические ВА-45 до 6300А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '05.02 Выключатели автоматические ВА-450 до 1600А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '06 Контакторы, пускатели, реле и аксессуары к ним до 1000А',
    children: [
      {
        name: '06.01 Контакторы малогабаритные КМЭ 9-95А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.02 Контакторы КТЭ 115-630А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.03 Контакторы модульные КМ 16-63А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.04 Пускатели магнитные КМЭ в корпусе IP65 9-95А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.05 Выключатели пуска двигателя АПД-32, АПД-80, GV2P до 80А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.06 Контакторы электромагнитные КТ-6000 100-630А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.07 Контакторы малогабаритные КМЭп с катушкой постоянного тока 9-95А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.08 Пускатель КМЭ в корпусе IP65 с индикатором 9-95А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.09 Миниконтакторы МКЭ 6-16А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.10 Реле промежуточные 5-10А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.12.01 Тепловое реле РТЭ',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.12.02 Приставки выдержки времени ПВЭ',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.12.03 Приставки контактные ПКЭ',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.12.04 Блокировочное устройство для КМЭ',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.12.05 Катушки управления КМЭ',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.12.06 Катушки управления КТЭ',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.12.07 Катушки управления КТ-6000',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.12.08 Дугогасительные камеры для КТ-6000',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.12.09 Держатели к тепловым реле РТЭ',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.12.10 Комплектующие к КТЭ реверс',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.13 Пускатели электромагнитные ПМ12 63-1000А EKF Basic',
        servicePeriod: '7',
        storagePeriod: '5',
        lifeTime: '10',
      },
      {
        name: '06.18 Пускатели реверсивные КМЭ с РТЭ IP44 9-95А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '06.19. Реле твердотельные 25-80 А',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '07 Автоматизация и управление (частотники, контроллеры, АВР, релейная автоматика)',
    children: [
      {
        name: '07.01 Преобразователи частоты EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '3',
        lifeTime: '7',
      },
      {
        name: '07.02 Преобразователи частоты EKF Basic',
        servicePeriod: '7',
        storagePeriod: '3',
        lifeTime: '7',
      },
      {
        name: '07.03.01 Автоматический ввод резерва ТСP1',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '07.03.02 Автоматический ввод резерва ТСМ',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '07.04 Программируемые реле EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '3',
        lifeTime: '10',
      },
      {
        name: '07.05.01 Таймеры электронные EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '07.05.02 Реле времени',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '07.05.03 Реле защиты двигателя серии MPR EKF',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '07.05.04 Реле контроля фаз',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '07.05.05 Реле напряжения',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '07.05.06 Реле уровня',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '07.05.07 Фотореле',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '07.05.08 Реле температуры',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '07.05.09 Импульсные реле',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '07.05.10 Ограничители мощности',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '07.05.11 Реле выбора фаз',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '07.05.12 Контроллеры АВР',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '07.06 Блоки питания',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '07.07 Стабилизаторы',
        servicePeriod: '7',
        storagePeriod: '3',
        lifeTime: '5',
      },
      {
        name: '07.08 ЭМС фильтры',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '08 Выключатели нагрузки, рубильники, разъединители, предохранители',
    children: [
      {
        name: '08.01 Выключатели нагрузки модульные AVN до 125А EKF AVERES',
        servicePeriod: '7',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '08.02 Выключатели нагрузки ВН-45 до 5000А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '08.03 Выключатели нагрузки ВН-99 до 800А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '08.04 Выключатели нагрузки модульные ВН-63, ВН-125 до 125А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '08.05 Выключатели-разъединители (рубильники) ВР32У MAXima до 630А',
        servicePeriod: '5',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '08.06 Выключатели-разъединители (рубильники) ВРЭ, УВРЭ до 630А EKF PROxima',
        servicePeriod: '5',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '08.07 Выключатели-разъединители (рубильники) УВРЭ вертикальные до 630А EKF PROxima',
        servicePeriod: '5',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '08.08 Рубильники модульные MS до 63А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '08.09 Разъединители РЕ19 до 3150А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '08.10 Разъединители РП (РПС, РПБ) до 630А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '08.11 Выключатели-разъединители (рубильники) TwinBlock до 1600А EKF PROxima',
        servicePeriod: '5',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '08.12 Предохранители плавкие ППН до 1250А EKF PROxima',
        servicePeriod: '5',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '08.13 Плавкие вставки цилиндрические ПВЦ до 80А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '08.14 Предохранители-разъединители для ПВЦ до 80А EKF PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '08.15 Выключатели нагрузки ВН-29 модульные до 63А EKF Basic',
        servicePeriod: '3',
        storagePeriod: '3',
        lifeTime: '8',
      },
      {
        name: '08.16 Трехпозиционные переключатели до 63А EKF Basic',
        servicePeriod: '3',
        storagePeriod: '3',
        lifeTime: '8',
      },
      {
        name: '08.17 Разъединители ПЦ до 400А',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '09 Кнопки, кнопочные посты, переключатели, светосигнальная арматура',
    children: [
      {
        name: '09.01.01 Индикаторы',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '09.01.02 Лампа сигнальная BV',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '09.01.03 Лампа сигнальная ENS-22',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '09.01.04 Лампа сменная неоновая',
        servicePeriod: '8',
        storagePeriod: '8',
        lifeTime: '11',
      },
      {
        name: '09.01.05 Лампа сменная светодиодная',
        servicePeriod: '9',
        storagePeriod: '9',
        lifeTime: '12',
      },
      {
        name: '09.01.06 Оповещатели',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '09.01.07 Светодиодная матрица AD-22HS',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '09.02 Кнопки',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '09.03 Кнопки "Грибок"',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '09.04 Переключатели',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '09.05 Сборная серия XB4',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '09.06 Дополнительные устройства для кнопок и переключателей',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '09.07 Кнопочные посты',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '09.08 Пульты',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '09.09 Выключатели кнопочные с блокировкой',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '09.10 Кулачковые переключатели',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '09.11.01 Концевые выключатели TZ',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '09.11.04 Путевые выключатели ВП 15',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '09.12 Пакетные выключатели и переключатели',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '10 Щиты распределительные навесные и встраиваемые',
    children: [
      {
        name: '10.01.01 Корпуса распределительные (ЩРн, ЩРв) IP31 PROxima',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '10.01.02 Корпуса распределительные (ЩРн) IP31 Basic',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '10.01.03 Корпуса распределительные (ЩРн) IP54 PROxima',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '10.01.04 Корпуса распределительные (ЩРн) IP54 Basic',
        servicePeriod: '3',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '10.02 Щиты распределительные пластиковые (ЩРН-П, ЩРВ-П) IP21/IP41',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '10',
      },
      {
        name: '10.03 Щиты распределительные пластиковые (ЩРН-П принт дерево) IP41',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '10',
      },
      {
        name: '10.04 Щиты распределительные пластиковые (КМПН) IP20/IP30',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '10.05 Щиты распределительные пластиковые герметичные (ЩРН-Пг) IP65',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '10.07 Щиты распределительные пластиковые SlimBox (ЩРН-П, ЩРВ-П) IP41',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '10',
      },
      {
        name: '10.13 Щиты распределительные пластиковые ProfiBox IP41',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '11 Щиты учетно-распределительные навесные и встраиваемые',
    children: [
      {
        name: '11.01 Щиты учетно-распределительные пластиковые герметичные (ЩУ-П, ЩУРн-П) IP54 / IP55',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '10',
      },
      {
        name: '11.02.01 ЩУРв',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '11.02.02 ЩУРн',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '11.02.03 ЩУРн с двумя отсеками (БУР)',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '11.03 Щиты учетные герметичные (ЩУ) IP54 PROxima',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
    ],
  },
  {
    name: '12 Щиты с монтажной панелью (автоматизации) навесные',
    children: [
      {
        name: '12.01.01 Корпуса с монтажной панелью (ЩМП IP31) PROxima',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '12.01.02 Корпуса с монтажной панелью (ЩМП IP31) Basic',
        servicePeriod: '3',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '12.01.03 Корпуса с монтажной панелью (ЩМПг IP54) PROxima',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '12.01.04 Корпуса с монтажной панелью (ЩМПг IP54) Basic',
        servicePeriod: '3',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '12.01.05 Корпуса с монтажной панелью (ЩМПг IP54 RAL 3001) PROxima',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '12.01.06 Монтажные панели для щитов ЩМП',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '12.02 Корпуса герметичные "Гранит" IP66',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '12.03 Корпуса из нержавеющей стали "Inox" IP66',
        servicePeriod: '5',
        storagePeriod: '10',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '13 Щиты и устройства этажные',
    children: [
      {
        name: '13.02 Щиты этажные EKF Basic',
        servicePeriod: '3',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '13.03 Щиты этажные EKF Basic усиленные',
        servicePeriod: '3',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '13.04 Корпуса УЭРМ EKF Basic',
        servicePeriod: '3',
        storagePeriod: '5',
        lifeTime: '5',
      },
    ],
  },
  {
    name: '14 Шкафы напольные металлические',
    children: [
      {
        name: '14.01 Шкафы ВРУ-1М',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.02.01 Комплектация для серии Unit',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.02.02 ВРУ-1 Unit R IP31 разборные',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.02.03 ВРУ-1 Unit S IP31 сварные',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.02.04 ВРУ-1 Unit S IP54 сварные',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.02.05 ВРУ-2 Unit S IP31 сварные',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.02.06 ВРУ-2 Unit S IP54 сварные',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.02.07 Корпус ЩО-70 Unit',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.03.01 Комплектация для ЩМП напольных',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.03.02 ЩМП напольные IP31',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.03.03 ЩМП напольные IP54',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.04 Шкафы ШРС',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.05 Пульты напольные TP IP55',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.06.01 Корпуса и боковые стенки IP31',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.06.02 Корпуса и боковые стенки IP54',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.06.03 Монтажные платы',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.06.04 Цоколи',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.06.05 Монтажные рейки',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.06.06 Комплекты стыковки',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '0',
      },
      {
        name: '14.06.07 Защита от прикосновений',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '14.07.01 Рамы',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '14.07.02 Двери',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '14.07.03 Внешние панели',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '14.07.04 Цоколь',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '14.07.05 Монтажные платы',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '14.07.06 Пластроны',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '14.07.07 Аксессуары',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '14.07.08 Секционирование',
        servicePeriod: '10',
        storagePeriod: '10',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '15 Низковольтные комплектные устройства (НКУ)',
    children: [
      {
        name: '15.01 Щиты ЯТП Basic',
        servicePeriod: '3',
        storagePeriod: '5',
        lifeTime: '5',
      },
    ],
  },
  {
    name: '16 Элементы комплектации шкафов',
    children: [
      {
        name: '16.01.01 DIN-рейки перфорированные',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '16.01.04 Кронштейны и зажимы для DIN-реек',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '16.02 Замки для щитов и накладки',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '16.03.01 Знаки безопасности (наклейки на пленке)',
        servicePeriod: 'без гарантии',
        storagePeriod: 'без гарантии',
        lifeTime: 'без гарантии',
      },
      {
        name: '16.03.02 Знаки безопасности (пластиковые таблички)',
        servicePeriod: 'без гарантии',
        storagePeriod: 'без гарантии',
        lifeTime: 'без гарантии',
      },
      {
        name: '16.04 Заглушки, карман для документации, поводки заземления, комплект монтажа, окна учета',
        servicePeriod: 'без гарантии',
        storagePeriod: 'без гарантии',
        lifeTime: 'без гарантии',
      },
      {
        name: '16.05 Ответвительный сжим (орех)',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.06 Распределительные блоки проходные РБП',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.07 Клеммы силовые вводные КСВ',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.08 Клеммные терминалы',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.09 Клеммные колодки JXB (винтовые)',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.10 Клеммные колодки JXB-S (пружинные)',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.11 Клеммные колодки JXB-ST (пружинные)',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.12 Бирка кабельная маркировочная',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.13 Шины соединительные (PIN, FORK) и аксессуары для шин',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.14.01 Медные шины',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.14.02 Алюминиевые шины',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.14.03 Шины медные гибкие изолированные 2м',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.15 Блоки клеммные КБР',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.16.01 Шины оцинкованные (N и PE)',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.16.02 Шины латунные (N и PE)',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.17 Нулевые шины в корпусе',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.18 Шинные распределительные блоки ШРБ',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.19.01 Изоляторы шинные SM бочонок',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.19.02 Изоляторы шинные Лесенка',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.19.03 Изоляторы шинные Мост',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.19.04 Изоляторы шинные SM бочонок без болта Basic',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.19.05 Изоляторы для шин N, PE (стойка и DIN-рейка)',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.19.06 Изоляторы для плоских шин',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.19.07 Система наборных шинодержателей',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.20 Кабельные вводы (сальники) и аксессуары к ним',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.20.01.01 Сальники герметичные PG (IP54) серые (20 шт)',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.20.01.02 Сальники герметичные PG (IP54) серые',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.21 Лента спиральная монтажная SWB',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.22 Площадка самоклеящаяся',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '16.23 Универсальный шинодержатель',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.24.01 Вентиляторы щитовые',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.24.02 Обогреватели',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.24.03 Термостаты и гигростаты',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.25 Универсальные терминалы для проводников',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '16.26 Кабель-маркер',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '17 Изделия для электромонтажа',
    children: [
      {
        name: '17.01.01 Наконечники медные луженые JG (ТМЛ) стандарт EKF',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
      {
        name: '17.01.02 Наконечники медные луженые ТМЛ ГОСТ 7386-80',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
      {
        name: '17.01.03 Наконечники медные DT (ТМ) стандарт EKF',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
      {
        name: '17.01.04 Наконечники медные ТМ ГОСТ 7386-80',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
      {
        name: '17.01.05 Наконечники медные луженые ТМЛ угловые (90гр.)',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
      {
        name: '17.01.06 Гильзы медные луженые GTY (ГМЛ) стандарт EKF',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
      {
        name: '17.01.07 Гильзы медные GT (ГМ) стандарт EKF',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
      {
        name: '17.01.08 Наконечники алюминиевые ТА ГОСТ 9581-80',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
      {
        name: '17.01.09 Гильзы алюминиевые ГОСТ 23469.2-79',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
      {
        name: '17.01.10 Наконечники кабельные алюмомедные (напыление) ТАМ',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
      {
        name: '17.01.11 Шайба алюмомедная ШАМ',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
      {
        name: '17.01.12 Наконечники медные луженые JG (ТМЛ) стандарт EKF в розничной упаковке',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
      {
        name: '17.01.13 Наконечники штифтовые медные луженые НШМЛ',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
      {
        name: '17.01.14 Наконечники штифтовые алюминиевые луженые НШАЛ',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
      {
        name: '17.01.15 Наконечники штифтовые алюминиевые НША',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
      {
        name: '17.03.01 Наконечник штыревой втулочный изолированный НШвИ, НШвИ2',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '17.03.02 Наконечник кольцевой изолированный НКИ',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '17.03.03 Наконечник вилочный изолированный НВИ',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '17.03.04 Наконечник штыревой плоский изолированный НШПИ',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '17.03.05 Наконечник штыревой круглый изолированный НШКИ',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '17.03.06 Наконечник кольцевой НК',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '17.03.07 Наконечник штыревой втулочный НШв',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '17.04 Разъемы изолированные',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '17.05 Гильзы соединительные изолированные',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '17.07 Клеммные колодки (зажим клеммный 12 секций)',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '17.08 Соединительные изолирующие зажимы (СИЗ)',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '17.09 Ответвители прокалывающие',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '17.10.01 Изолента ПВХ Basic',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '17.10.02 Изолента ХБ',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '17.11.01 ТУТ в рулонах',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '17.11.02 ТУТ в отрезках по 1 м',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '17.11.03 ТУТ в розничной упаковке',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '17.12.01 Хомуты FlexLock белые',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '17.12.02 Хомуты FlexLock черные',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '17.12.03 Дюбель-хомуты',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '17.12.04 Хомуты с отверстиями, площадками, анкерные',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '17.12.05 Хомуты белые (кабельный бандаж) Basic',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '17.12.06 Хомуты черные (кабельный бандаж) Basic',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '17.12.07 Хомуты FlexLock белые для DIY',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '17.12.08 Хомуты FlexLock черные для DIY',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '17.12.09 Наборы хомутов в банках FlexLock',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '17.12.10 Хомуты FlexLock из нержавеющей стали (304)',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '17.12.11 Хомуты FlexLock из нержавеющей стали (316)',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '17.12.13 Аксессуары для хомутов',
        servicePeriod: '1',
        storagePeriod: '2',
        lifeTime: '3',
      },
      {
        name: '17.13 Скобы крепежные пластиковые',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '18 Инструмент',
    children: [
      {
        name: '18.01 Отвертки индикаторные EKF',
        servicePeriod: '1',
        storagePeriod: '1',
        lifeTime: '1',
      },
      {
        name: '18.02.01 Мультиметры',
        servicePeriod: '1',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '18.02.02 Токовые клещи',
        servicePeriod: '1',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '18.02.03 Контрольно-измерительные приборы',
        servicePeriod: '1',
        storagePeriod: '10',
        lifeTime: '10',
      },
      {
        name: '18.03.01 Отвертки',
        servicePeriod: '1',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '18.03.02 Шарнирно-губцевый инструмент',
        servicePeriod: '1',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '18.04.01 Диэлектрические отвертки',
        servicePeriod: '1',
        storagePeriod: '5',
        lifeTime: '5',
      },
      {
        name: '18.04.02 Диэлектрический шарнирно-губцевый инструмент',
        servicePeriod: '1',
        storagePeriod: '5',
        lifeTime: '5',
      },
    ],
  },
  {
    name: '19 Трансформаторы измерительные',
    servicePeriod: '7',
    storagePeriod: '7',
    lifeTime: '25',
  },
  {
    name: '20 Счетчики электроэнергии',
    children: [
      {
        name: '20.01 Счетчики электрической энергии SKAT однофазные',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '30',
      },
      {
        name: '20.02 Счетчики электрической энергии SKAT трехфазные',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '30',
      },
    ],
  },
  {
    name: '21 Приборы измерительные',
    children: [
      {
        name: '21.05 Амперметры аналоговые AMA-721 со сменными шкалами',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '10',
      },
      {
        name: '21.06 Многофункциональные измерители',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '10',
      },
      {
        name: '21.07 Амперметр аналоговый AMA-961 со сменными шкалами',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '22 Розетки, выключатели',
    children: [
      {
        name: '22.01 Серия Лондон (скрытая установка) IP20',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '22.02 Серия Венеция (открытая установка) IP54',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '22.03 Серия Прага (открытая установка) IP44',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '22.04 Серия Рим (открытая установка) IP20',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '22.05 Серия Мурманск (открытая установка) IP54',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
      {
        name: '22.06.01 Серия Минск цвет белый',
        servicePeriod: '3',
        storagePeriod: '3',
        lifeTime: '7',
      },
      {
        name: '22.06.02 Серия Минск цвет светлое дерево',
        servicePeriod: '3',
        storagePeriod: '3',
        lifeTime: '7',
      },
      {
        name: '22.06.03 Серия Минск цвет тёмное дерево',
        servicePeriod: '3',
        storagePeriod: '3',
        lifeTime: '7',
      },
      {
        name: '22.07 Серия Минск (скрытая установка) IP20',
        servicePeriod: '3',
        storagePeriod: '3',
        lifeTime: '7',
      },
      {
        name: '22.08 Дополнительные устройства в розетку',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '23 Удлинители, сетевые фильтры, патроны и аксессуары',
    servicePeriod: '7',
    storagePeriod: '7',
    lifeTime: '10',
  },
  {
    name: '24 Силовые разъемы',
    servicePeriod: '7',
    storagePeriod: '7',
    lifeTime: '10',
  },
  {
    name: '25 Управление освещением, аварийное освещение, бытовые звонки',
    servicePeriod: '7',
    storagePeriod: '7',
    lifeTime: '10',
  },
  {
    name: '26 Системы обогрева',
    servicePeriod: '7',
    storagePeriod: '7',
    lifeTime: '10',
  },
  {
    name: '27 Кабеленесущие системы',
    servicePeriod: '7',
    storagePeriod: '7',
    lifeTime: '10',
  },
  {
    name: '28 Арматура и инструмент для монтажа СИП',
    children: [
      {
        name: '28.01 Кронштейны и элементы креплений',
        servicePeriod: '5',
        storagePeriod: '5',
        lifeTime: '25',
      },
      {
        name: '28.02 Зажимы',
        servicePeriod: '8',
        storagePeriod: '5',
        lifeTime: '25',
      },
      {
        name: '28.03 Инструмент для монтажа СИП',
        servicePeriod: '1',
        storagePeriod: '3',
        lifeTime: '5',
      },
      {
        name: '28.04 Расходники для монтажа СИП',
        servicePeriod: '5',
        storagePeriod: '2',
        lifeTime: '25',
      },
    ],
  },
  {
    name: '29 Шинопроводы',
    children: [
      {
        name: '29.01 Шинопровод магистральный Hyperion',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
      {
        name: '29.04 Комплектующие',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
    ],
  },
  {
    name: '30 Молниезащита и заземление',
    children: [
      {
        name: '30.01.01 Молниеприемники пассивные',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
      {
        name: '30.01.03 Держатели кровельные',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '',
      },
      {
        name: '30.01.04 Держатели на конек',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
      {
        name: '30.01.05 Держатели на конек регулируемые',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
      {
        name: '30.01.06 Держатели под черепицу (профлист)',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
      {
        name: '30.01.07 Держатели для водосточных трубу',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
      {
        name: '30.01.08 Держатели проводника на трубе',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
      {
        name: '30.01.09 Держатели круглых и плоских проводников',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
      {
        name: '30.01.10 Держатели фасадные',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
      {
        name: '30.01.11 Держатели фальцевые',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
      {
        name: '30.01.12 Зажимы',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
      {
        name: '30.02.02 Штанги изолированные',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
      {
        name: '30.03.01 Комплекты заземления',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
      {
        name: '30.03.02 Элементы заземления',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
      {
        name: '30.04 Проводники плоские и круглые',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
      {
        name: '30.05 Дополнительные элементы',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '25',
      },
    ],
  },
  {
    name: '31 Лотки металлические, STRUT-система',
    children: [
      {
        name: '31.01 Лотки перфорированные T-Line EKF',
        servicePeriod: '3',
        storagePeriod: '3.5',
        lifeTime: '20',
      },
      {
        name: '31.01 Лотки перфорированные T-Line EKF',
        servicePeriod: '3',
        storagePeriod: '7.5',
        lifeTime: '20',
      },
      {
        name: '31.02 Лотки неперфорированные T-Line EKF',
        servicePeriod: '3',
        storagePeriod: '3.5',
        lifeTime: '20',
      },
      {
        name: '31.02 Лотки неперфорированные T-Line EKF',
        servicePeriod: '3',
        storagePeriod: '7.5',
        lifeTime: '20',
      },
      {
        name: '31.03 Крышки для металлического лотка EKF',
        servicePeriod: '3',
        storagePeriod: '3.5',
        lifeTime: '20',
      },
      {
        name: '31.03 Крышки для металлического лотка EKF',
        servicePeriod: '3',
        storagePeriod: '7.5',
        lifeTime: '20',
      },
      {
        name: '31.03 Крышки для металлического лотка EKF',
        servicePeriod: '3',
        storagePeriod: '4',
        lifeTime: '20',
      },
      {
        name: '31.05.05 Хомуты металлические (трубные)',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '15',
      },
      {
        name: '31.07.03 STRUT монтажные элементы',
        servicePeriod: '3',
        storagePeriod: '3',
        lifeTime: '20',
      },
      {
        name: '31.08 Лотки лестничные M-Line EKF',
        servicePeriod: '3',
        storagePeriod: '3.5',
        lifeTime: '',
      },
      {
        name: '31.08 Лотки лестничные M-Line EKF',
        servicePeriod: '7',
        storagePeriod: '7.5',
        lifeTime: '20',
      },
      {
        name: '31.10 Лотки проволочные R-Line EKF',
        servicePeriod: '3',
        storagePeriod: '3.5',
        lifeTime: '20',
      },
    ],
  },
  {
    name: '32 Умный дом',
    servicePeriod: '3',
    storagePeriod: '3',
    lifeTime: '10',
  },
  {
    name: '33 Устройства сбора и передачи данных',
    servicePeriod: '6',
    storagePeriod: '3',
    lifeTime: '3',
  },
  {
    name: '34 Элементы коррекции коэффициента мощности',
    children: [
      {
        name: '34.02 Регуляторы для устройств компенсации реактивной мощности',
        servicePeriod: '2',
        storagePeriod: '3',
        lifeTime: '7',
      },
      {
        name: '34.04.01 Контакторы для конденсаторных батарей (КРМ) до 50квар PROxima',
        servicePeriod: '7',
        storagePeriod: '7',
        lifeTime: '10',
      },
    ],
  },
  {
    name: '35 Свет',
    servicePeriod: '2',
    storagePeriod: '2',
    lifeTime: '10',
  },
  {
    name: '50 Оборудование среднего напряжения Stingray',
    children: [
      {
        name: '50.01 Выключатели нагрузки 10кВ',
        servicePeriod: '3',
        storagePeriod: '5',
        lifeTime: '25',
      },
      {
        name: '50.02 Разъединители 10кВ',
        servicePeriod: '3',
        storagePeriod: '5',
        lifeTime: '25',
      },
      {
        name: '50.06 Трансформаторы тока 10кВ',
        servicePeriod: '5',
        storagePeriod: '3',
        lifeTime: '30',
      },
      {
        name: '50.07 Трансформаторы напряжения до 10кВ',
        servicePeriod: '5',
        storagePeriod: '3',
        lifeTime: '30',
      },
      {
        name: '50.08 Релейная защита',
        servicePeriod: '3',
        storagePeriod: '2',
        lifeTime: '8',
      },
      {
        name: '50.10 Корпуса КСО',
        servicePeriod: '1',
        storagePeriod: '1.5',
        lifeTime: '25',
      },
    ],
  },
]

export default {}
